Repository replicatedhq/replicated-sdk, pull requests merged in 2023-09, with the labels that each got.

#79 API to accept metrics from application
  pact/custom_metrics_test.go
  pkg/apiserver/server.go
  pkg/handlers/custom_metrics.go
  pkg/handlers/custom_metrics_test.go
  pkg/metrics/metrics.go
Labels: type::feature

#83 Make the chart/api work with helm template + kubectl
  .github/actions/validate-endpoints/action.yml
  .github/workflows/main.yaml
  chart/templates/_helpers.tpl
  chart/templates/replicated-sdk-configmap.yaml
  chart/templates/replicated-sdk-deployment.yaml
  chart/templates/replicated-sdk-role.yaml
  chart/templates/replicated-sdk-rolebinding.yaml
  chart/templates/replicated-sdk-secret.yaml
  chart/templates/replicated-sdk-service.yaml
  chart/templates/replicated-sdk-serviceaccount.yaml
  chart/templates/replicated-sdk-supportbundle.yaml
  chart/values.yaml.tmpl
  pact/heartbeat_test.go
  pact/license_test.go
  pkg/apiserver/bootstrap.go
  pkg/appstate/operator.go
  pkg/handlers/app.go
  pkg/heartbeat/app.go
  pkg/heartbeat/heartbeat.go
  pkg/heartbeat/util.go
  pkg/heartbeat/util_test.go
  pkg/helm/helm.go
  pkg/k8sutil/fake.go
  pkg/util/env.go
  pkg/util/replicated.go
Labels: type::feature

#84 Add missing request headers
  pact/custom_metrics_test.go
Labels: type::chore

#86 use better env var names for the test-chart
  .github/workflows/main.yaml
  test-chart/Chart.yaml.tmpl
Labels: type::chore

#87 Create Github release on tag
  .github/workflows/publish.yaml
Labels: type::chore

#88 Lookup the dynamic configmap name instead of 'replicated'
  chart/templates/_helpers.tpl
  chart/templates/replicated-configmap.yaml
  chart/templates/replicated-deployment.yaml
  pkg/util/replicated.go
Labels: bug::normal, type::bug

#91 Remove authorization header from custom metrics API
  pact/custom_metrics_test.go
  pkg/handlers/custom_metrics.go
Labels: bug::normal, type::bug

#90 chore: Add replicated app info collector and analyser
  chart/templates/replicated-supportbundle.yaml
Labels: type::chore
