Repository replicatedhq/replicated-sdk, pull requests merged in 2023-08, with the labels that each got.

#63 generate release notes PR on release
  .github/workflows/publish.yaml
Labels: type::docs

#33 Use Chainguard Image for Replicated SDK
  .github/workflows/main.yaml
  Dockerfile
Labels: type::feature

#64 pass previous tag as base to release notes generator
  .github/workflows/publish.yaml
Labels: type::docs

#68 Include the app status as part of the /app/info endpoint and refactor how mock data is handled
  chart/templates/replicated-sdk-deployment.yaml
  chart/templates/replicated-sdk-secret.yaml
  pkg/handlers/app.go
  pkg/integration/data/default_mock_data.yaml
  pkg/integration/data/test_mock_data.yaml
  pkg/integration/integration.go
  pkg/integration/integration_test.go
  pkg/integration/mock.go
  pkg/integration/mock_test.go
  pkg/integration/types/types.go
Labels: type::feature

#69 add license sync pacts
  pact/license_test.go
Labels: type::chore

#73 add record support ended, add record release to staging
  .github/workflows/publish.yaml
  Makefile
Labels: type::chore

#74 Don't drop pact support for older Replicated SDK versions
  .github/workflows/publish.yaml
  Makefile
Labels: type::chore

#77 Add support for OpenShift clusters
  chart/templates/_helpers.tpl
  chart/templates/replicated-sdk-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature
