Repository replicatedhq/replicated-sdk, pull requests merged in 2023-10, with the labels that each got.

#94 add checksum annotation for replicated-secret
  .github/actions/validate-endpoints/action.yml
  .github/workflows/main.yaml
  chart/templates/replicated-deployment.yaml
Labels: bug::normal, type::bug

#96 Add extra env to helm template
  .github/workflows/main.yaml
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature, type::improvement

#97 fix pact testing cache in ci
  .github/workflows/main.yaml
Labels: type::chore

#99 Don't panic on nil values
  pkg/handlers/custom_metrics.go
  pkg/handlers/custom_metrics_test.go
Labels: bug::normal, type::bug

#101 Add an endpoint to the SDK where metrics can be retrieved adhoc
  .github/actions/validate-endpoints/action.yml
  pact/custom_metrics_test.go
  pkg/apiserver/server.go
  pkg/handlers/app.go
  pkg/handlers/app_test.go
  pkg/handlers/custom_metrics.go
  pkg/handlers/middleware.go
  pkg/handlers/types/types.go
  pkg/heartbeat/util.go
  pkg/heartbeat/util_test.go
  pkg/metrics/metrics.go
Labels: type::feature

#104 feat: allow a user to define tolerations (e.g. multi arch clusters, specific nodes, etc)
  .github/workflows/main.yaml
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature, type::improvement

#102 allow empty status informers
  .github/workflows/main.yaml
  chart/templates/replicated-secret.yaml
  chart/values.yaml.tmpl
  pkg/apiserver/bootstrap.go
  pkg/appstate/util.go
Labels: type::feature, type::improvement

#105 Send app status related info only if initialized
  pkg/apiserver/bootstrap.go
  pkg/appstate/operator.go
  pkg/heartbeat/app.go
  pkg/heartbeat/util.go
  pkg/heartbeat/util_test.go
  pkg/store/memory_store.go
  pkg/upstream/replicated.go
Labels: bug::normal, type::bug

#107 remove app metrics endpoint
  .github/actions/validate-endpoints/action.yml
  pkg/apiserver/server.go
  pkg/handlers/app.go
Labels: type::chore

#106 support airgap heartbeat
  .github/actions/validate-endpoints/action.yml
  .github/workflows/main.yaml
  .gitignore
  chart/templates/replicated-role.yaml
  chart/templates/replicated-supportbundle.yaml
  pkg/heartbeat/app.go
  pkg/heartbeat/app_test.go
  pkg/heartbeat/heartbeat.go
  pkg/heartbeat/instance_report.go
  pkg/heartbeat/instance_report_test.go
  pkg/heartbeat/types/types.go
  pkg/heartbeat/util.go
  pkg/store/mock/mock_store.go
  pkg/util/compress.go
  pkg/util/replicated.go
  pkg/util/replicated_test.go
Labels: type::feature

#108 UserAgent should not be configurable
  .github/workflows/main.yaml
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
  pact/license_test.go
  pkg/buildversion/buildversion.go
Labels: type::chore

#109 Don't publish pact on PR or merge to main
  .github/workflows/main.yaml
Labels: type::chore

#111 user_agent in airgap instance report
  pkg/heartbeat/app.go
  pkg/heartbeat/instance_report_test.go
  pkg/heartbeat/types/types.go
Labels: type::feature, type::improvement

#110 Ability for the SDK API to handle being installed in a KOTS airgap scenario
  .github/actions/validate-endpoints/action.yml
  .github/workflows/main.yaml
  pkg/handlers/app.go
Labels: type::feature

#113 remove unnecessary ghcr.io login action
  .github/workflows/publish.yaml
Labels: type::chore

#114 images.replicated-sdk instead of images.replicated
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature

#115 Handle race condition where events are reported out of order
  pkg/heartbeat/app.go
Labels: bug::normal, type::bug
