Repository replicatedhq/replicated-sdk, pull requests merged in 2023-07, with the labels that each got.

#49 split unit and pact tests
  Makefile
  README.md
  pact/heartbeat_test.go
  pact/pact_test.go
Labels: type::chore

#50 install pact for publish.yaml
  .github/workflows/publish.yaml
Labels: type::chore

#51 check for pact cli when running test-pact
  Makefile
Labels: type::chore

#58 silence api cmd usage
  cmd/replicated/api.go
  cmd/replicated/main.go
Labels: type::feature, type::improvement

#42 add default-http-backend ingress service when k8s version is < 1.22
  pkg/appstate/ingress.go
  pkg/appstate/ingress_test.go
  pkg/k8sutil/clientset.go
  pkg/k8sutil/clientset_test.go
Labels: bug::regression, type::bug

#59 remove gke autopilot distro check
  pkg/heartbeat/app.go
  pkg/heartbeat/distribution.go
  pkg/heartbeat/distribution_test.go
  pkg/heartbeat/types/types.go
  pkg/k8sutil/clientset.go
Labels: bug::normal, type::bug

#57 Lessen the default RBAC permissions
  chart/templates/replicated-configmap.yaml
  chart/templates/replicated-role.yaml
  pkg/apiserver/bootstrap.go
  pkg/integration/integration.go
  pkg/integration/mock.go
  pkg/integration/mock_test.go
  pkg/util/replicated.go
Labels: type::feature

#60 import kotskinds from dedicated repo
  cmd/replicated/api.go
  go.mod
  go.sum
  pact/heartbeat_test.go
  pkg/apiserver/server.go
  pkg/appstate/ingress.go
  pkg/appstate/ingress_test.go
  pkg/handlers/license.go
  pkg/heartbeat/util.go
  pkg/integration/integration.go
  pkg/integration/integration_test.go
  pkg/license/license.go
  pkg/license/signature.go
  pkg/license/util.go
  pkg/store/memory_store.go
  pkg/store/mock/mock_store.go
  pkg/store/store_interface.go
  pkg/upstream/replicated.go
  pkg/util/env.go
Labels: type::chore
