Repository replicatedhq/replicated-sdk, pull requests merged in 2024-02, with the labels that each got.

#140 add default fsGroup and supplementalGroups to podSecurityContext
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature, type::improvement

#143 bump helm and go to resolve cves
  .github/workflows/main.yaml
  .github/workflows/publish.yaml
  Dockerfile
  go.mod
  go.sum
Labels: type::security

#148 Build replicated sdk with chainguard
  .github/actions/build-push-action/action.yml
  .github/workflows/daily-scan.yaml
  .github/workflows/main.yaml
  .github/workflows/publish.yaml
  Makefile
  deploy/Dockerfile
  deploy/apko.yaml.tmpl
  deploy/melange.yaml.tmpl
  go.mod
  go.sum
Labels: type::feature

#151 Group dependabot updates
  .github/dependabot.yml
Labels: type::security

#153 Fix publishing Helm chart
  .github/workflows/publish.yaml
Labels: type::chore
