Repository replicatedhq/replicated-sdk, pull requests merged in 2024-10, with the labels that each got.

#210 feat: template helm image properties
  .github/workflows/main.yaml
  .github/workflows/publish.yaml
  chart/templates/_helpers.tpl
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature

#211 stop using v in version
  CONTRIBUTING.md
Labels: type::feature

#213 Use listReleases instead of listTags
  .github/workflows/publish.yaml
Labels: bug::regression, type::bug

#214 Use ref_name as current tag value
  .github/workflows/publish.yaml
Labels: bug::regression, type::bug

#216 Bump helm version to clear warning for CVE-2024-41110
  go.mod
  go.sum
Labels: type::chore

#215 Ability to specify additional CA using a secret name/key
  Makefile
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature
