Repository replicatedhq/replicated-sdk, pull requests merged in 2024-06, with the labels that each got.

#184 specify namespace in logs collector
  .github/workflows/main.yaml
  chart/templates/replicated-supportbundle.yaml
Labels: bug::normal, type::bug

#188 Update Kubernetes versions we test on
  .github/workflows/main.yaml
Labels: type::chore

#186 Use exec collectors instead of http for support bundles
  .github/workflows/main.yaml
  chart/templates/replicated-supportbundle.yaml
  pkg/handlers/app.go
  pkg/handlers/license.go
Labels: type::feature

#191 feat[sc-100944]: Support upserting and deleting custom metrics
  pact/custom_metrics_test.go
  pkg/apiserver/server.go
  pkg/handlers/app.go
  pkg/k8sutil/fake.go
  pkg/meta/instance_tags.go
  pkg/meta/latest_custom_metrics.go
  pkg/meta/latest_custom_metrics_test.go
  pkg/meta/meta.go
  pkg/meta/types/types.go
  pkg/meta/types/types_test.go
  pkg/report/custom_app_metrics.go
  pkg/report/instance.go
  pkg/report/types/types.go
  pkg/report/util_test.go
Labels: type::feature

#192 Add default timeout for HTTP client
  pkg/license/license.go
  pkg/report/custom_app_metrics.go
  pkg/report/instance.go
  pkg/upstream/replicated.go
  pkg/util/http.go
Labels: type::chore
