Repository replicatedhq/replicated-sdk, pull requests merged in 2024-07, with the labels that each got.

#193 feat [sc 106247]: Add a caching layer to prevent SDK from sending the same payloads too frequently upstream
  pkg/apiserver/server.go
  pkg/handlers/middleware.go
  pkg/handlers/middleware_test.go
  pkg/util/http_client.go
Labels: type::feature

#195 Channels pact
  pact/license_test.go
Labels: type::chore

#198 fix: [sc-109535] k8s minor version parsing error
  pkg/k8sutil/clientset.go
  pkg/k8sutil/clientset_test.go
Labels: bug::normal, type::bug
