Repository replicatedhq/replicated-sdk, pull requests merged in 2025-01, with the labels that each got.

#235 Detect cluster versions supported by CMX
  .github/actions/cmx-versions/.gitignore
  .github/actions/cmx-versions/action.yaml
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/actions/cmx-versions/package-lock.json
  .github/actions/cmx-versions/package.json
  .github/workflows/main.yaml
Labels: type::feature

#236 Enable dev mode for the license in e2e tests
  .github/workflows/main.yaml
Labels: type::chore

#241 Bump golang.org/x/net to 0.34.0
  go.mod
  go.sum
Labels: type::security
