Repository replicatedhq/replicated-sdk, pull requests merged in 2025-02, with the labels that each got.

#244 feat: add ability to pass custom labels
  chart/templates/_helpers.tpl
  chart/templates/replicated-deployment.yaml
  chart/values.yaml.tmpl
Labels: type::feature

#247 Use ttl.sh for daily scans
  .github/workflows/daily-scan.yaml
Labels: type::chore

#250 Scan the most recent release for CVEs
  .github/workflows/daily-scan.yaml
Labels: type::security
