Repository replicatedhq/replicated-sdk, pull requests merged in 2025-04, with the labels that each got.

#267 Update cmx_versions action to use Ubuntu 22.04 to avoid brownouts
  .github/actions/generate-support-bundle/action.yml
  .github/workflows/main.yaml
Labels: type::chore

#266 feat: helm chart improvements
  chart/templates/_helpers.tpl
  chart/templates/replicated-clusterrolebinding.yaml
  chart/templates/replicated-configmap.yaml
  chart/templates/replicated-deployment.yaml
  chart/templates/replicated-role.yaml
  chart/templates/replicated-rolebinding.yaml
  chart/templates/replicated-secret.yaml
  chart/templates/replicated-service.yaml
  chart/templates/replicated-serviceaccount.yaml
  chart/templates/replicated-supportbundle.yaml
  chart/values.yaml.tmpl
Labels: type::feature

#269 Build updates
  .github/workflows/publish.yaml
  .github/workflows/validate.yml
  .gitignore
  Makefile
  RELEASE.md
  chart/Chart.yaml
  chart/Chart.yaml.tmpl
  chart/scripts/build-ttl.sh
  chart/values.yaml
  dagger.json
  dagger/.gitattributes
  dagger/.gitignore
  dagger/README.md
  dagger/build.go
  dagger/cmx.go
  dagger/e2e.go
  dagger/go.mod
  dagger/go.sum
  dagger/main.go
  dagger/replicated.go
  dagger/secret.go
  dagger/test.go
  dagger/validate.go
  test-chart/Chart.yaml
Labels: type::chore

#270 triggers are globs, not really regex
  .github/workflows/publish.yaml
Labels: type::chore

#271 create test release is in dagger
  .github/workflows/publish.yaml
  .github/workflows/validate.yml
Labels: type::chore

#272 Publish via dagger
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/build-push-action/action.yml
  .github/actions/cmx-versions/.gitignore
  .github/actions/cmx-versions/action.yaml
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/actions/cmx-versions/package-lock.json
  .github/actions/cmx-versions/package.json
  .github/actions/generate-support-bundle/action.yml
  .github/actions/validate-endpoints/action.yml
  .github/workflows/publish.yaml
  .github/workflows/publish.yml
  .github/workflows/slsa.yml
  RELEASE.md
  chart/values.yaml
  dagger.json
  dagger/README.md
  dagger/build.go
  dagger/chainguard.go
  dagger/chart.go
  dagger/cmx.go
  dagger/e2e.go
  dagger/go.mod
  dagger/go.sum
  dagger/publish.go
  dagger/release-notes.go
  dagger/replicated.go
  dagger/secret.go
  dagger/test.go
  deploy/apko.yaml
  deploy/melange.yaml
  deploy/melange.yaml.tmpl
  go.mod
  go.sum
Labels: type::chore

#274 Fix cross compile in action runner
  .github/workflows/publish.yml
  dagger/chainguard.go
Labels: type::chore

#275 push a release when finished
  .github/workflows/publish.yml
  dagger/publish.go
Labels: type::chore

#277 Bump golang.org/x/net and github.com/containerd/containerd
  go.mod
  go.sum
Labels: type::security
